name: Unit tests

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: macos-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Cache Build Dependencies
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache/flutter
            /Users/runner/hostedtoolcache/flutter
            /Users/runner/.pub-cache
          key: unit-${{ runner.os }}-build
          restore-keys: |
            unit-${{ runner.os }}-build

      - name: Configure Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Unit Tests
        run: |
          flutter test --coverage \
            --test-randomize-ordering-seed=random \
            --file-reporter json:build/unit/reports/unit-test-results.json

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

#      Poniższy krok służy do usunięcia pokrycia kodu dla wygenerowanych plików, użyte przykłady
#      '*.g.dart' oraz 'lib/generated/**' należy podmienić wszystkimi plikami generowanymi
#      w danym repozytorium
      - name: Remove Code Coverage for Generated Files
        run: |
          lcov --remove coverage/lcov.info -o coverage/lcov.info --ignore-errors unused,unused \
            '*.g.dart' \
            'lib/generated/**' \
            'lib/login_page.dart'

      - name: lcov Code Coverage Report
        uses: JoA-MoS/lcov-reporter-action@v1.0.0-alpha.4
        with:
          delete-old-comments: true

#       Inne narzędzie do publikowania wyników testów
#      - name: Publish iOS Unit Test Report
#        uses: EnricoMi/publish-unit-test-result-action/macos@v2
#        if: always()
#        with:
#          check_name: "Unit Test Results"
#          files: |
#            build/unit/reports/unit-test-results.json

      - name: Test Reporting
        uses: phoenix-actions/test-reporting@v15
        id: test-report-unit              # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit Tests          # Name of the check run which will be created
          path: build/unit/reports/unit-test-results.json    # Path to test results
          reporter: flutter-json